TRANSLATIONS = \
    translation/xapkd_de.ts \
    translation/xapkd_es.ts \
    translation/xapkd_fr.ts \
    translation/xapkd_he.ts \
    translation/xapkd_it.ts \
    translation/xapkd_ja.ts \
    translation/xapkd_ko.ts \
    translation/xapkd_pl.ts \
    translation/xapkd_pt_BR.ts \
    translation/xapkd_pt_PT.ts \
    translation/xapkd_ru.ts \
    translation/xapkd_tr.ts\
    translation/xapkd_vi.ts \
    translation/xapkd_zh.ts \
    translation/xapkd_zh_TW.ts

FORMS += \
    ../FormatDialogs/dialogdump.ui \
    ../FormatDialogs/dialogdumpprocess.ui \
    ../FormatDialogs/dialoggotoaddress.ui \
    ../FormatDialogs/dialoghexsignature.ui \
    ../FormatDialogs/dialoginfo.ui \
    ../FormatDialogs/dialogsearch.ui \
    ../FormatDialogs/dialogsearchprocess.ui \
    ../FormatDialogs/dialogtextinfo.ui \
    ../FormatWidgets/Binary/binarywidget.ui \
    ../FormatWidgets/Binary/dialogbinary.ui \
    ../FormatWidgets/DEX/dexsectionheaderwidget.ui \
    ../FormatWidgets/DEX/dexwidget.ui \
    ../FormatWidgets/DEX/dialogdex.ui \
    ../FormatWidgets/ELF/dialogelf.ui \
    ../FormatWidgets/ELF/elfsectionheaderwidget.ui \
    ../FormatWidgets/ELF/elfwidget.ui \
    ../FormatWidgets/LE/dialogle.ui \
    ../FormatWidgets/LE/lesectionheaderwidget.ui \
    ../FormatWidgets/LE/lewidget.ui \
    ../FormatWidgets/MACH/dialogmach.ui \
    ../FormatWidgets/MACH/machsectionheaderwidget.ui \
    ../FormatWidgets/MACH/machwidget.ui \
    ../FormatWidgets/MACHOFAT/machofatwidget.ui \
    ../FormatWidgets/MSDOS/dialogmsdos.ui \
    ../FormatWidgets/MSDOS/msdoswidget.ui \
    ../FormatWidgets/MultiSearch/dialogmultisearchprocess.ui \
    ../FormatWidgets/NE/dialogne.ui \
    ../FormatWidgets/NE/nesectionheaderwidget.ui \
    ../FormatWidgets/NE/newidget.ui \
    ../FormatWidgets/PE/dialogpe.ui \
    ../FormatWidgets/PE/pesectionheaderwidget.ui \
    ../FormatWidgets/PE/pewidget.ui \
    ../FormatWidgets/SearchSignatures/dialogsearchsignatures.ui \
    ../FormatWidgets/SearchSignatures/searchsignatureswidget.ui \
    ../FormatWidgets/SearchStrings/dialogsearchstrings.ui \
    ../FormatWidgets/SearchStrings/searchstringswidget.ui \
    ../FormatWidgets/dialogprocessdata.ui \
    ../FormatWidgets/dialogsectionheader.ui \
    ../FormatWidgets/formatswidget.ui \
    ../FormatWidgets/toolswidget.ui \
    ../QHexView/dialoghex.ui \
    ../QHexView/qhexviewwidget.ui \
    ../StaticScan/dialogstaticscan.ui \
    ../StaticScan/dialogstaticscanprocess.ui \
    ../StaticScan/formresult.ui \
    ../StaticScan/formstaticscan.ui \
    ../StaticScan/heurwidget.ui \
    ../XDemangleWidget/dialogdemangle.ui \
    ../XDemangleWidget/xdemanglewidget.ui \
    ../XDisasm/dialogasmsignature.ui \
    ../XDisasm/dialogdisasm.ui \
    ../XDisasm/dialogdisasmlabels.ui \
    ../XDisasm/dialogdisasmprocess.ui \
    ../XDisasm/xdisasmwidget.ui \
    ../XDisasmView/dialogmultidisasm.ui \
    ../XDisasmView/dialogmultidisasmsignature.ui \
    ../XDisasmView/xmultidisasmwidget.ui \
    ../XEntropyWidget/dialogentropy.ui \
    ../XEntropyWidget/dialogentropyprocess.ui \
    ../XEntropyWidget/xentropywidget.ui \
    ../XHashWidget/dialoghash.ui \
    ../XHashWidget/dialoghashprocess.ui \
    ../XHashWidget/xhashwidget.ui \
    ../XHexView/dialoghexview.ui \
    ../XHexView/xhexviewwidget.ui \
    ../XMemoryMapWidget/dialogmemorymap.ui \
    ../XMemoryMapWidget/xmemorymapwidget.ui \
    ../XShortcuts/dialogshortcuts.ui \
    ../archive_widget/archive_widget.ui \
    ../archive_widget/dialogarchive.ui \
    ../archive_widget/dialogcreateviewmodel.ui \
    ../archive_widget/dialogshowimage.ui \
    ../archive_widget/dialogshowtext.ui \
    ../archive_widget/dialogunpackfile.ui \
    dialogabout.ui \
    dialogdirectoryscan.ui \
    dialogoptions.ui \
    guimainwindow.ui \
    ../nfd_widget/nfd_widget.ui

SOURCES += \
    ../Controls/hexvalidator.cpp \
    ../Controls/subclassofqstyleditemdelegate.cpp \
    ../Controls/xabstracttableview.cpp \
    ../Controls/xcomboboxex.cpp \
    ../Controls/xdatetimeeditx.cpp \
    ../Controls/xdevicetableview.cpp \
    ../Controls/xlineedithex.cpp \
    ../FormatDialogs/dialogdumpprocess.cpp \
    ../FormatDialogs/dialoggotoaddress.cpp \
    ../FormatDialogs/dialoghexsignature.cpp \
    ../FormatDialogs/dialoginfo.cpp \
    ../FormatDialogs/dialogsearch.cpp \
    ../FormatDialogs/dialogsearchprocess.cpp \
    ../FormatDialogs/dialogtextinfo.cpp \
    ../FormatDialogs/dumpprocess.cpp \
    ../FormatDialogs/searchprocess.cpp \
    ../FormatWidgets/Binary/binary_defs.cpp \
    ../FormatWidgets/Binary/binarywidget.cpp \
    ../FormatWidgets/Binary/dialogbinary.cpp \
    ../FormatWidgets/DEX/dex_defs.cpp \
    ../FormatWidgets/DEX/dexprocessdata.cpp \
    ../FormatWidgets/DEX/dexsectionheaderwidget.cpp \
    ../FormatWidgets/DEX/dexwidget.cpp \
    ../FormatWidgets/DEX/dialogdex.cpp \
    ../FormatWidgets/ELF/dialogelf.cpp \
    ../FormatWidgets/ELF/elf_defs.cpp \
    ../FormatWidgets/ELF/elfprocessdata.cpp \
    ../FormatWidgets/ELF/elfsectionheaderwidget.cpp \
    ../FormatWidgets/ELF/elfwidget.cpp \
    ../FormatWidgets/LE/dialogle.cpp \
    ../FormatWidgets/LE/le_defs.cpp \
    ../FormatWidgets/LE/leprocessdata.cpp \
    ../FormatWidgets/LE/lesectionheaderwidget.cpp \
    ../FormatWidgets/LE/lewidget.cpp \
    ../FormatWidgets/MACH/dialogmach.cpp \
    ../FormatWidgets/MACH/mach_defs.cpp \
    ../FormatWidgets/MACH/machprocessdata.cpp \
    ../FormatWidgets/MACH/machsectionheaderwidget.cpp \
    ../FormatWidgets/MACH/machwidget.cpp \
    ../FormatWidgets/MACHOFAT/machofatwidget.cpp \
    ../FormatWidgets/MSDOS/dialogmsdos.cpp \
    ../FormatWidgets/MSDOS/msdos_defs.cpp \
    ../FormatWidgets/MSDOS/msdoswidget.cpp \
    ../FormatWidgets/MultiSearch/dialogmultisearchprocess.cpp \
    ../FormatWidgets/MultiSearch/multisearch.cpp \
    ../FormatWidgets/NE/dialogne.cpp \
    ../FormatWidgets/NE/ne_defs.cpp \
    ../FormatWidgets/NE/neprocessdata.cpp \
    ../FormatWidgets/NE/nesectionheaderwidget.cpp \
    ../FormatWidgets/NE/newidget.cpp \
    ../FormatWidgets/PE/dialogpe.cpp \
    ../FormatWidgets/PE/pe_defs.cpp \
    ../FormatWidgets/PE/peprocessdata.cpp \
    ../FormatWidgets/PE/pesectionheaderwidget.cpp \
    ../FormatWidgets/PE/pewidget.cpp \
    ../FormatWidgets/SearchSignatures/dialogsearchsignatures.cpp \
    ../FormatWidgets/SearchSignatures/searchsignatureswidget.cpp \
    ../FormatWidgets/SearchStrings/dialogsearchstrings.cpp \
    ../FormatWidgets/SearchStrings/searchstringswidget.cpp \
    ../FormatWidgets/dialogprocessdata.cpp \
    ../FormatWidgets/dialogsectionheader.cpp \
    ../FormatWidgets/formatswidget.cpp \
    ../FormatWidgets/formatwidget.cpp \
    ../FormatWidgets/invwidget.cpp \
    ../FormatWidgets/processdata.cpp \
    ../FormatWidgets/toolswidget.cpp \
    ../Formats/subdevice.cpp \
    ../Formats/xbinary.cpp \
    ../Formats/xcom.cpp \
    ../Formats/xelf.cpp \
    ../Formats/xformats.cpp \
    ../Formats/xle.cpp \
    ../Formats/xmach.cpp \
    ../Formats/xmsdos.cpp \
    ../Formats/xne.cpp \
    ../Formats/xpe.cpp \
    ../QHexView/dialoghex.cpp \
    ../QHexView/qhexview.cpp \
    ../QHexView/qhexviewwidget.cpp \
    ../SpecAbstract/signatures.cpp \
    ../SpecAbstract/specabstract.cpp \
    ../StaticScan/dialogstaticscan.cpp \
    ../StaticScan/dialogstaticscanprocess.cpp \
    ../StaticScan/formresult.cpp \
    ../StaticScan/formstaticscan.cpp \
    ../StaticScan/heurwidget.cpp \
    ../StaticScan/staticscan.cpp \
    ../StaticScan/staticscanitem.cpp \
    ../StaticScan/staticscanitemmodel.cpp \
    ../XArchive/xarchive.cpp \
    ../XArchive/xarchives.cpp \
    ../XArchive/xcab.cpp \
    ../XArchive/xmachofat.cpp \
    ../XArchive/xrar.cpp \
    ../XArchive/xsevenzip.cpp \
    ../XArchive/xzip.cpp \
    ../XCapstone/xcapstone.cpp \
    ../XDEX/xandroidbinary.cpp \
    ../XDEX/xdex.cpp \
    ../XDemangle/xdemangle.cpp \
    ../XDemangleWidget/dialogdemangle.cpp \
    ../XDemangleWidget/xdemanglewidget.cpp \
    ../XDisasm/dialogasmsignature.cpp \
    ../XDisasm/dialogdisasm.cpp \
    ../XDisasm/dialogdisasmlabels.cpp \
    ../XDisasm/dialogdisasmprocess.cpp \
    ../XDisasm/xdisasm.cpp \
    ../XDisasm/xdisasmmodel.cpp \
    ../XDisasm/xdisasmwidget.cpp \
    ../XDisasmView/dialogmultidisasm.cpp \
    ../XDisasmView/dialogmultidisasmsignature.cpp \
    ../XDisasmView/xdisasmview.cpp \
    ../XDisasmView/xmultidisasmwidget.cpp \
    ../XEntropyWidget/dialogentropy.cpp \
    ../XEntropyWidget/dialogentropyprocess.cpp \
    ../XEntropyWidget/entropyprocess.cpp \
    ../XEntropyWidget/xentropywidget.cpp \
    ../XHashWidget/dialoghash.cpp \
    ../XHashWidget/dialoghashprocess.cpp \
    ../XHashWidget/hashprocess.cpp \
    ../XHashWidget/xhashwidget.cpp \
    ../XHexEdit/xhexedit.cpp \
    ../XHexView/dialoghexview.cpp \
    ../XHexView/xhexview.cpp \
    ../XHexView/xhexviewwidget.cpp \
    ../XLLVMDemangler/3rdparty/llvm/Demangle/Demangle.cpp \
    ../XLLVMDemangler/3rdparty/llvm/Demangle/ItaniumDemangle.cpp \
    ../XLLVMDemangler/3rdparty/llvm/Demangle/MicrosoftDemangle.cpp \
    ../XLLVMDemangler/3rdparty/llvm/Demangle/MicrosoftDemangleNodes.cpp \
    ../XMemoryMapWidget/dialogmemorymap.cpp \
    ../XMemoryMapWidget/xmemorymapwidget.cpp \
    ../XOptions/xoptions.cpp \
    ../XShortcuts/dialogshortcuts.cpp \
    ../XShortcuts/xshortcuts.cpp \
    ../XShortcuts/xshortcutsdialog.cpp \
    ../XShortcuts/xshortcutstscrollarea.cpp \
    ../XShortcuts/xshortcutswidget.cpp \
    ../archive_widget/archive_widget.cpp \
    ../archive_widget/createviewmodelprocess.cpp \
    ../archive_widget/dialogarchive.cpp \
    ../archive_widget/dialogcreateviewmodel.cpp \
    ../archive_widget/dialogshowimage.cpp \
    ../archive_widget/dialogshowtext.cpp \
    ../archive_widget/dialogunpackfile.cpp \
    ../archive_widget/unpackfileprocess.cpp \
    ../console_source/main_console.cpp \
    dialogabout.cpp \
    dialogdirectoryscan.cpp \
    dialogoptions.cpp \
    guimainwindow.cpp \
    main_gui.cpp





